---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: tknaac-bindings
spec:
  params:
    - name: github_json
      value: $(body)
    - name: installation_id
      value: $(body.installation.id)
    - name: application_id
      value: "81262"
