# Tekton yaml
owners:
  - "@openshift-pipelines"

# Install tasks from catalog
tasks:
  - git-clone
  - yaml-lint
  - https://raw.githubusercontent.com/chmouel/catalog/master/task/pylint/0.2/pylint.yaml
  - shellcheck

# Apply those files in order in the .tekton directory
files:
  - pipeline.yaml
  - run.yaml
